[package]
name = "nexuslauncher"
version = "0.1.1"
description = "NexusLauncher - launcher de Minecraft con control de instancias para el owner"
authors = ["Kaz"]
edition = "2021"

[lib]
name = "nexuslauncher_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "stream", "gzip", "rustls-tls-native-roots"] }
tokio = { version = "1", features = ["full"] }
sha2 = "0.10"
base64 = "0.22"
rand = "0.8"
zip = { version = "2", default-features = false, features = ["deflate"] }
url = "2"
percent-encoding = "2"
serde_urlencoded = "0.7"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
open = "5"
dirs = "5"
futures-util = "0.3"
regex = "1"
once_cell = "1"
log = "0.4"
x25519-dalek = { version = "2", features = ["static_secrets"] }
discord-rich-presence = "1.1.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = "symbols"
